#!/bin/bash

set -euo pipefail

echo "--- Preparing plugin"
DL="${BUILDKITE_PLUGIN_APTLY_PUBLISH_DOWNLOAD:-}"
DIST="${BUILDKITE_PLUGIN_APTLY_PUBLISH_DISTRIBUTION:-stretch}"

if [[ "${BUILDKITE_PLUGIN_APTLY_PUBLISH_SLUG:-false}" =~ (true|on|1) ]] ; then
  DL="${DL}/${BUILDKITE_PIPELINE_SLUG}"
  echo "New download: $DL"
fi

if [[ -n "$BUILDKITE_TAG" ]]; then
  REL=testing
else
  REL=unstable
fi

if [[ "$DIST" == "jessie" ]]; then
  repo="opx-$REL"
  endpoints=(
    "s3:opx:"
    "s3:opx:$DIST"
  )
else
  if [[ -n "$BUILDKITE_TAG" ]]; then
    repo="opx-$DIST"
  else
    repo="opx-$REL-$DIST"
  fi
  endpoints=(
    "s3:opx:$DIST"
  )
fi

echo "+++ Publishing packages to $repo"
cd ..
buildkite-agent artifact download "$DL/*" .

mapfile -t CHANGES < <(find "$DL" -maxdepth 1 -name '*.changes')
if [[ "${#CHANGES[@]}" -gt 0 ]]; then
  # we have a changes file to submit
  aptly repo include -keyring=AD5073F1 -repo="$repo" -accept-unsigned "$DL"/*.changes
else
  # submit bare deb files
  aptly repo add -remove-files "$repo" "$DL"/*.deb
fi

for e in "${endpoints[@]}"; do
  aptly publish update "$REL" "$e"
done
echo "--- Updating http://deb.openswitch.net/apt.svg"
aptly graph -format=svg -layout=vertical -output=apt.svg
aws s3 cp apt.svg s3://deb.openswitch.net/ --acl public-read
