#!/bin/bash

set -euo pipefail

args=(
  "-distribution="
)

DL="${BUILDKITE_PLUGIN_APTLY_PUBLISH_DOWNLOAD:-}"
DIST="${BUILDKITE_PLUGIN_APTLY_PUBLISH_DISTRIBUTION:-stretch}"

if [[ -n "$BUILDKITE_TAG" ]]; then
  REL=testing
else
  REL=unstable
fi

if [[ "$DIST" == "jessie" ]]; then
  repo="opx-$REL"
  endpoints=(
    "s3:opx:"
    "s3:opx:$DIST"
  )
else
  if [[ -n "$BUILDKITE_TAG" ]]; then
    repo="opx-$DIST"
  else
    repo="opx-$REL-$DIST"
  fi
  endpoints=(
    "s3:opx:$DIST"
  )
fi

echo "+++ Publishing packages to $repo"
cd ..
shopt -s extglob
buildkite-agent artifact download "$DL"/* .
aptly repo include -keyring=AD5073F1 -repo="$repo" -accept-unsigned "$DL"/*.changes
for e in "${endpoints[@]}"; do
  aptly publish update "$REL" "$e"
done
echo "--- Updating http://deb.openswitch.net/apt.svg"
aptly graph -format=svg -layout=vertical -output=apt.svg
aws s3 cp apt.svg s3://deb.openswitch.net/ --acl public-read
